events {}

http {
    upstream flink-jobmanager {
        server flink-jobmanager:8081;
    }

    server {
        listen 443 ssl;
        # server_name localhost;

        ssl_certificate       /etc/ssl/certs/nginx-cert.pem;
        ssl_certificate_key  /etc/ssl/private/nginx-key.pem;

        # Enable SSL client authentication
        ssl_client_certificate /etc/ssl/certs/ca-cert.pem; # Specify the CA certificate used to sign client certs
        ssl_verify_client on;                          # Enable client certificate verification

        location / {
            proxy_pass http://flink-jobmanager;  # Replace with your backend service
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
