global:
  scrape_interval: 15s

rule_files:
  - 'flink.rules.yml'
scrape_configs:
  - job_name: 'flink'
    metrics_path: /
    static_configs:
      - targets: ['flink-jobmanager:9125', 'flink-taskmanager:9125']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
